docs(tree): Upgrade the use case of tree component to Composition API
TuSimple/naive-ui pull request #1034
Opened 2021-09-01 05:34 UTC by songjianet

2021-09-01 05:50 UTC, Volankey requested changes

2021-09-01 05:50 UTC, Volankey commented on src/tree/demos/enUS/async.demo.md
> +  if (!currentLabel) return '道生一'
英文的变成中文了

2021-09-01 05:50 UTC, Volankey commented on src/tree/demos/zhCN/drag-drop.demo.md
> +  if (level === 4) return 'Out of Tao, One is born'
中文的变英文了

2021-09-01 06:20 UTC, songjianet commented on src/tree/demos/zhCN/drag-drop.demo.md
> +  if (level === 4) return 'Out of Tao, One is born'
写完了一个，直接复制的

2021-09-01 09:03 UTC, Volankey approved these changes

2021-09-01 16:43 UTC, 07akioni commented on src/tree/demos/zhCN/drag-drop.demo.md
>   */
/**
 * 这个例子的时间复杂度确实可以优化 我实在是懒得改了
 */

2021-09-02 16:40 UTC, 07akioni commented
![image](https://user-images.githubusercontent.com/18677354/131883419-4d992866-4ce7-4df2-b58a-027f5c02b1ed.png)

@songjianet 全小写

2021-09-02 16:40 UTC, merged