feat(n-timeline): add 'icon' slot
TuSimple/naive-ui pull request #1103
Opened 2021-09-06 03:30 UTC by LYErin

close #1096

2021-09-06 07:10 UTC, afocus commented
期待icon 图标可以在大一点 看起来更加美观。

2021-09-06 07:27 UTC, LYErin commented
> 期待icon 图标可以在大一点 看起来更加美观。
已优化

2021-09-06 07:28 UTC, LYErin commented
> 期待icon 图标可以在大一点 看起来更加美观。

已优化

2021-09-06 10:51 UTC, Volankey requested changes

2021-09-06 10:51 UTC, Volankey commented on CHANGELOG.zh-CN.md
> +- `n-timeline` 增加 `icon` slot, 关闭 [#1096](https://github.com/TuSimple/naive-ui/issues/1096).
```suggestion
- `n-timeline` 增加 `icon` slot, 关闭 [#1096](https://github.com/TuSimple/naive-ui/issues/1096)
```

2021-09-06 10:51 UTC, Volankey commented on src/timeline/demos/enUS/index.demo-entry.md
> +| icon    | `()`       | Timeline item cutomize icon                    |
Customize timeline icon.

2021-09-06 10:51 UTC, Volankey commented on src/timeline/styles/dark.ts
> +      iconColor: textColor3,
TimelineItem.tsx 的 props 里面有 `color` 和 `type`，没必要这里再搞一个 `cssvar` 传出去

2021-09-06 10:51 UTC, Volankey commented on src/timeline/styles/light.ts
> +    iconColorInfo: infoColor,
同上

2021-09-06 10:51 UTC, Volankey commented on src/timeline/src/styles/index.cssr.ts
> +      cE('icon', `
个人感觉既然 `icon` 需要自定义渲染，这里的大小颜色 margin 等都不该由组件控制了，可以等 @07akioni 看看再决定要不要修改

2021-09-06 10:51 UTC, Volankey commented on src/timeline/src/TimelineItem.tsx
> +            [createKey('iconColor', type)]: iconColor
iconColor没用，this.color 有颜色

2021-09-06 10:51 UTC, Volankey commented on src/timeline/src/TimelineItem.tsx
> +              {renderSlot(this.$slots, 'icon')}
个人感觉为什么还要 `timline` 组件自己的 `color` 呢? 可以把 `type` 传到插槽中，让用户自定义每个 `type` 对应的颜色
```
  {renderSlot(this.$slots, 'icon',{ color:this.color, type: this.type })}
```

可以等 @07akioni  看看决定要不要改

2021-09-06 17:48 UTC, 07akioni commented on src/timeline/src/styles/index.cssr.ts
> +      cE('icon', `
如果挂在 n-icon 里面的话应该是没事的，比如 transition，只留一些必要的样式就行

2021-09-06 17:48 UTC, 07akioni commented on src/timeline/styles/dark.ts
> +      iconColor: textColor3,
这里可能还是得传的，不然没有 color 值可以用

2021-09-07 01:02 UTC, LYErin commented on src/timeline/src/TimelineItem.tsx
> +            [createKey('iconColor', type)]: iconColor
> iconColor没用，this.color 有颜色

这个iconColor对应传的是type的颜色

2021-09-07 01:13 UTC, LYErin commented on src/timeline/styles/dark.ts
> +      iconColor: textColor3,
> 这里可能还是得传的，不然没有 color 值可以用

这边改成默认取type的颜色，如果props有传入color，就覆盖type的颜色

2021-09-07 01:13 UTC, LYErin commented on src/timeline/styles/dark.ts
> +      iconColor: textColor3,
这边改成默认取type的颜色，如果props有传入color，就覆盖type的颜色

2021-09-07 01:31 UTC, LYErin commented on src/timeline/src/styles/index.cssr.ts
> +      cE('icon', `
> 如果挂在 n-icon 里面的话应该是没事的，比如 transition，只留一些必要的样式就行

如果不设置大小，图标会很小，样式不美观

2021-09-07 01:31 UTC, LYErin commented on src/timeline/src/styles/index.cssr.ts
> +      cE('icon', `
如果不设置大小，图标会很小，样式不美观

2021-09-07 17:37 UTC, 07akioni commented on src/timeline/src/styles/index.cssr.ts
> +      cE('icon', `
确实是这么回事，应该说尽量从视觉上和原来的圈不要有太大差别吧

2021-09-07 17:38 UTC, merged