feat: avatar lazyload
TuSimple/naive-ui pull request #3154
Opened 2022-06-21 12:19 UTC by Innei

2022-06-21 15:45 UTC, amadeus711 requested changes

2022-06-21 15:45 UTC, amadeus711 commented on src/avatar/demos/enUS/index.demo-entry.md
>  | Name | Type | Default | Description |
此处列表格式不对，少一列 version，下面新增的 API 的 version 填 NEXT_VERSION

2022-06-21 15:45 UTC, amadeus711 commented on src/avatar/demos/zhCN/index.demo-entry.md
>  | 名称 | 类型 | 默认值 | 说明 |
此处列表格式不对，少一列版本，下面新增的 API 的版本填 NEXT_VERSION

2022-06-21 15:45 UTC, amadeus711 commented on src/avatar/src/Avatar.tsx
> +              // @ts-expect-error
处理报错

2022-06-21 15:45 UTC, amadeus711 commented on src/image/src/Image.tsx
> +        // @ts-expect-error
处理报错

2022-06-21 16:57 UTC, 07akioni commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
expect error 这是个神马意图？
然后这个和 intersection observer 不冲突吗？

2022-06-22 02:31 UTC, Innei commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
vue 没有这个属性。。。但是可以看看 mdn 是有这个原生属性的。

2022-06-22 02:34 UTC, keuby commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
`loading` 的兼容性貌似挺有问题的，他要 chrome 77 才支持

2022-06-22 04:06 UTC, amadeus711 commented on src/avatar/demos/enUS/index.demo-entry.md
>  | Name | Type | Default | Description |
表格表头还是少一列

2022-06-22 04:06 UTC, amadeus711 commented on src/avatar/demos/zhCN/index.demo-entry.md
>  | 名称 | 类型 | 默认值 | 说明 |
表格表头还是少一列

2022-06-22 05:26 UTC, 07akioni commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
> `loading` 的兼容性貌似挺有问题的，他要 chrome 77 才支持

77 倒不是啥大问题，18 年就有了

2022-06-22 05:27 UTC, 07akioni commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
我的意思是如果说 lazy 可用的话，有必要和 intersection observer 共存吗？是否在支持 lazy 的时候就不应该用 intersection observer？

2022-06-22 05:28 UTC, 07akioni commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
> vue 没有这个属性。。。但是可以看看 mdn 是有这个原生属性的。

感觉你可以去蹭一个 vue 的 PR

2022-06-22 06:16 UTC, Innei commented on src/avatar/src/Avatar.tsx
> +              loading={lazy ? 'lazy' : 'eager'}
我去蹭下

2022-06-22 07:34 UTC, Innei commented on src/image/src/Image.tsx
> +    const loadSrc: string = this.src || (imageProps.src as any as string)
为什么 imageProps.src 推导出了 StringConstructor

2022-06-26 17:44 UTC, 07akioni commented on src/image/src/Image.tsx
> +    const loadSrc: string = this.src || (imageProps.src as any as string)
母鸡，搞不太懂是啥问题

2022-06-26 17:44 UTC, 07akioni commented on src/image/src/Image.tsx
> +
```suggestion
```

2022-06-28 17:58 UTC, 07akioni commented
我周末看看吧，关键是去掉那个 expect error 啥的，还要保证正确

2022-06-29 03:33 UTC, Innei commented on src/image/src/Image.tsx
> +    const loadSrc: string = this.src || (imageProps.src as any as string)
ts 类型推断错了。不知道为啥，`props: { src: String }` 在 render 的 props 推断了 src 是 `StringConstructor `...

2022-07-03 05:36 UTC, merged

2022-07-03 05:53 UTC, 07akioni commented on src/image/src/Image.tsx
> +    const loadSrc: string = this.src || (imageProps.src as any as string)
是你写错了，应该是 imgSrc

2022-07-03 05:57 UTC, 07akioni commented
把 jsx 换成 h 就解决了