fix(select): fix NSelect bug in using custom label
TuSimple/naive-ui pull request #382
Opened 2021-07-05 06:53 UTC by amadeus711

fix #352

2021-07-05 07:36 UTC, Volankey requested changes

2021-07-05 07:36 UTC, Volankey commented on src/_internal/selection/src/Selection.tsx
> +                default: () =>
感觉抽成一个函数好一点
```
default: syneticRenderLabel(option,label,true)
```

2021-07-05 07:42 UTC, Volankey commented on src/_internal/selection/src/Selection.tsx
> +                default: () =>
仔细看了一下感觉直接在 render(option.label,renderLabel, option, true)这个函数里面做这些逻辑会更好点
我在想如果既传了`renderLabel`又传了`label:()=>h(xxx) `那是否应该以` label:()=>h(xxx) `优先级更高?

2021-07-05 07:56 UTC, amadeus711 commented
https://github.com/TuSimple/naive-ui/pull/382#discussion_r663708258
render() 函数是工具函数，只用于根据传入的不同类型的值进行 dom 渲染。这里我是遵循了菜单等地方的 renderLabel 的习惯写的，即 renderLabel 优先级更高。如果想实现不同 label 的渲染，可以在 options 内挂载自定义项，并在 renderLabel 内根据自定义项判断渲染。

2021-07-05 14:15 UTC, 07akioni commented on src/_internal/selection/src/Selection.tsx
> +        ? render(props.selectedOption.label, props.selectedOption, selectedRef)
```suggestion
        ? render(props.selectedOption.label, props.selectedOption, true)
```

2021-07-05 14:15 UTC, 07akioni commented on src/_internal/selection/src/Selection.tsx
> +                default: () =>
我们之前也想过，但是感觉 emmm，就直接来吧，你既然都传了 renderLabel 就不要再想着用 render function 定制了，至少我还没想到有啥需求

2021-07-05 14:15 UTC, 07akioni commented on src/_internal/selection/src/Selection.tsx
> +              )}
这块 format 过吗，看起来格式不太对

2021-07-05 14:15 UTC, 07akioni commented on src/_internal/selection/src/styles/index.cssr.ts
> +        color: var(--text-color);
这是不是和 placeholder 有很多重复？有的话提一下

2021-07-06 02:36 UTC, Volankey commented on CHANGELOG.en-US.md
> +- Fix `n-select` bug in using custom label, closes [#352](https://github.com/TuSimple/naive-ui/issues/352)
放到pending里面

2021-07-06 02:36 UTC, Volankey commented on CHANGELOG.zh-CN.md
> +- 修复 `n-select` 自定义 label 的显示问题，关闭 [#352](https://github.com/TuSimple/naive-ui/issues/352)
放到pending里面

2021-07-06 15:46 UTC, 07akioni commented on CHANGELOG.en-US.md
> +- Fix `n-select` bug in using custom label, closes [#352](https://github.com/TuSimple/naive-ui/issues/352)
```suggestion
- Fix `n-select` bug in using custom label, closes [#352](https://github.com/TuSimple/naive-ui/issues/352).
```

2021-07-06 15:46 UTC, 07akioni commented on src/_internal/selection/src/Selection.tsx
> +import { RenderLabel, RenderLabelImpl } from '../../select-menu/src/interface'
```suggestion
import type { RenderLabel, RenderLabelImpl } from '../../select-menu/src/interface'
```

2021-07-06 15:47 UTC, merged