feat(NButton): add text-color prop
TuSimple/naive-ui pull request #762
Opened 2021-08-02 10:01 UTC by amadeus711

2021-08-02 11:32 UTC, Volankey requested changes

2021-08-02 11:32 UTC, Volankey commented on src/button/src/Button.tsx
> +              textColor ||
这地方disabled情况下会不会很丑

2021-08-02 15:01 UTC, amadeus711 commented on src/button/src/Button.tsx
> +              textColor ||
我认为用户既然要自定义文字颜色，就该自己考虑到 disabled 情况

2021-08-03 08:25 UTC, Volankey approved these changes

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +              ? createHoverColor(textColor)
```suggestion
              ? textColor
```

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +              ? createPressedColor(textColor)
```suggestion
              ? textColor
```

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +              ? createHoverColor(textColor)
```suggestion
              ? textColor
```

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +        const mergedTextColor = textColor || color
放到下面的分支去

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +          const mergedTextColorPlus =
这命名不可取

2021-08-03 16:24 UTC, 07akioni commented on src/button/src/Button.tsx
> +          const mergedTextColorPlus =
可把 mergedTextColor 改成 propTextColor，mergedTextColorPlus 改成 mergedTextColor

2021-08-04 15:28 UTC, merged