feature/form: add `show-label` prop
TuSimple/naive-ui pull request #865
Opened 2021-08-13 08:15 UTC by kev1nzh37

#858

2021-08-13 09:33 UTC, Volankey requested changes
实现参考一下 `showRequireMark`

2021-08-13 09:33 UTC, Volankey commented on CHANGELOG.en-US.md
> +- `n-form` add `show-label` prop.
Add close xxx

2021-08-13 09:34 UTC, Talljack commented on CHANGELOG.en-US.md
> +- `n-form` add `show-label` prop.
```suggestion
- `n-form` add `show-label` prop, closes [#858](https://github.com/TuSimple/naive-ui/issues/858).
```

2021-08-13 09:34 UTC, Talljack commented on CHANGELOG.zh-CN.md
> +- `n-form` 新增 `show-label` 属性
```suggestion
- `n-form` 新增 `show-label` 属性，关闭 [#858 ](https://github.com/TuSimple/naive-ui/issues/858)
```

2021-08-13 10:05 UTC, kev1nzh37 commented
> 实现参考一下 `showRequireMark`,form及form-item都应该有

好的，明天我加一下

2021-08-13 14:38 UTC, amadeus711 commented
尝试加一下测试吧

2021-08-13 14:48 UTC, 07akioni commented
加一个 Demo，然后按照我的理解，不展示 label 的情况下应该也没有 label 占位，所以样式也需要修改。

2021-08-14 01:46 UTC, kev1nzh37 commented
收到。

2021-08-15 13:46 UTC, Volankey commented on src/form/src/FormItem.tsx
> +          (!this.mergedShowLabel || this.label === false) &&
`(!this.mergedShowLabel || this.label === false)`这里的逻辑包括下面的 `this.mergedShowLabel && (this.label || $slots.label)` 看起来都在判断label是否要显示,是否都可以融入utils里面的mergedShowLabel？

2021-08-15 16:43 UTC, kev1nzh37 commented on src/form/src/FormItem.tsx
> +          (!this.mergedShowLabel || this.label === false) &&
我之前实现了，提交时考虑到 show-label 和 label 都在 mergedShowLabel 中是否不恰当才分开的。后天上班我再提交下，辛苦啦。

2021-08-17 16:34 UTC, kev1nzh37 commented
似乎逻辑上有点问题，我明天继续看下。

2021-08-18 04:00 UTC, kev1nzh37 commented
逻辑似乎不能融合进 mergedShowLabelRef, 因为 no-label 这个 class 和 label的内容没关系。把代码还原回来了。

2021-08-18 16:39 UTC, 07akioni commented
LGTM

2021-08-18 16:56 UTC, 07akioni commented on CHANGELOG.en-US.md
> +- `n-form` add `show-label` prop, closes [#858](https://github.com/TuSimple/naive-ui/issues/858).
这个的位置得改一下，挪到没发布的版本

2021-08-18 16:56 UTC, 07akioni commented on CHANGELOG.zh-CN.md
>  - `n-message-provider` 新增 `container-style` 属性
挪一下位置

2021-08-18 16:56 UTC, 07akioni commented on src/form/demos/enUS/index.demo-entry.md
> +| show-label | `boolean` | `true` | Whether to show label. |
这个应该放到 35 行

```
show-required-mark > show-label > show-feedback
```

2021-08-18 16:56 UTC, 07akioni commented on src/form/demos/enUS/index.demo-entry.md
> +| show-label | `boolean` | `true` | Whether to show label. If not set, use `show-label` from wrapper form. |
prop name 顺序

2021-08-18 17:00 UTC, 07akioni reviewed
![image](https://user-images.githubusercontent.com/18677354/129940250-97d2cc77-47db-4dd5-9248-b4c9730c5b74.png)

这个是期望的效果。

我研究了一下，好像 label = false 就能关掉 label，这个是目前已经实现的，通过 `n-form-item--no-label` 这个类。我们可以通过 `show-label` 来控制这个行为，**然后不允许 `label` 传  bool了**。剩下的和现在一致。

2021-08-18 17:45 UTC, kev1nzh37 commented
> ![image](https://user-images.githubusercontent.com/18677354/129940250-97d2cc77-47db-4dd5-9248-b4c9730c5b74.png)
> 
> 这个是期望的效果。
> 
> 我研究了一下，好像 label = false 就能关掉 label，这个是目前已经实现的，通过 `n-form-item--no-label` 这个类。我们未来只通过 `show-label` 来控制这个行为，**然后不允许 `label` 传  bool了**。剩下的和现在一致。

了解了，白天提交。

2021-08-19 17:38 UTC, 07akioni commented on CHANGELOG.en-US.md
> +
```suggestion
```

2021-08-19 17:38 UTC, 07akioni commented on CHANGELOG.zh-CN.md
> +- `n-form` 新增 `show-label` 属性，关闭 [#858 ](https://github.com/TuSimple/naive-ui/issues/858)
```suggestion
- `n-form` 新增 `show-label` 属性，关闭 [#858](https://github.com/TuSimple/naive-ui/issues/858)
```

2021-08-19 17:39 UTC, 07akioni commented on src/form/src/FormItem.tsx
>    },
这种可以直接写成 `type: String`

2021-08-19 17:39 UTC, merged

2021-08-19 17:45 UTC, 07akioni commented on src/form/demos/zhCN/show-label.demo.md
> +`n-form-item` 若未被设定，则会使用外层 `n-form` 的 `show-label`, 若都未被设定，则默认为 `true`。
```
`show-label`: 当值为

`show-label`：当值为
```

```
bel`, 若都

bel`，若都
```

标点的使用可以注意一下