feat(dropdown): options add onClick prop
TuSimple/naive-ui pull request #951
Opened 2021-08-24 03:56 UTC by bljessica

Closes #813

2021-08-24 04:10 UTC, 07akioni commented
Add `props` to `option`, like data table row.

2021-08-24 05:53 UTC, Volankey commented
Like the follow code, pass the option's props to option render.
```
{
  label: "Brown's Hotel, London",
  key: "brown's hotel, london",
  props:{
    onClick: () => {
      message.info('Okay')
    },
  }
}
```

2021-08-24 10:58 UTC, Volankey commented
If options is disabled,  what `onClick` prop should do? @07akioni

2021-08-25 05:05 UTC, 07akioni commented
> If options is disabled, what `onClick` prop should do? @07akioni

fired

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/demos/enUS/index.demo-entry.md
> +| props | `{onClick: () => void}` | Customize event handling. |
```suggestion
| props | `{onClick: () => void}` | Customize event handling. |
```

这个地方应该是 HTMLElement 能接受的所有属性

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/demos/zhCN/index.demo-entry.md
> +| props    | `{onClick: () => void}` | 自定义事件处理                  |
同上

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/DropdownMenu.tsx
> +              optionProps={tmNode.rawNode.props}
```suggestion
              props={tmNode.rawNode.props}
```

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +      type: Object as PropType<DropdownOptionProps | null>,
```suggestion
      type: Object as PropType<DropdownOptionProps | null>,
```

这个地方应该是 HTMLDivAttributes 之类的东西，从 vue 中导出的

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +      type: Object as PropType<DropdownOptionProps | null>,
default 不是 null，直接写 props: Object 就行了，默认是 undefined

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        }
这段清除掉

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        }
props 直接 spread 到 render 函数中的 option 的 div 上

2021-08-25 05:09 UTC, 07akioni commented on src/dropdown/src/interface.ts
> +  props?: DropdownOptionProps
类型也顺便改一下

2021-08-25 05:13 UTC, Volankey commented on src/dropdown/src/DropdownOption.tsx
> +        }
如果props里面的onClick存在的话要触发现在的handleClick吗？

2021-08-25 05:23 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        }
要出发，这个就完全留给用户自己定义了，随便搞吧

2021-08-25 10:06 UTC, Volankey requested changes

2021-08-25 10:06 UTC, Volankey commented on src/dropdown/demos/enUS/index.demo-entry.md
> +event-handling
感觉这个叫 `event-handling` 不太ok

2021-08-25 10:06 UTC, Volankey commented on src/dropdown/demos/enUS/index.demo-entry.md
> +event-handling
option-props

2021-08-25 10:06 UTC, Volankey commented on src/dropdown/src/DropdownOption.tsx
> +      ...props
这样写就覆盖了之前的事件，期望是两处的事件都会被触发
```
onMousemove: this.handleMouseMove,
onMouseenter: this.handleMouseEnter,
onMouseleave: this.handleMouseLeave,
```
用vue提供的 mergeProps 来做

2021-08-25 10:06 UTC, Volankey commented on src/dropdown/src/DropdownOption.tsx
> +      ...props
![image](https://user-images.githubusercontent.com/23287363/130771547-11170e31-7567-4adf-80c8-1eae77f090e3.png)

2021-08-25 15:52 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        props as VNodeProps
类型不用这么写，我们还是尽量保持 JSX。

VNodeProps 是 vue 内部的一个属性，这么写还不如 any。

一个错误的 as 还不如 any。

```
const optionBodyProps: HTMLAttributes = {
          class: [
            `${clsPrefix}-dropdown-option-body`,
            {
              [`${clsPrefix}-dropdown-option-body--pending`]: this.pending,
	@@ -224,48 +232,55 @@ export default defineComponent({
              [`${clsPrefix}-dropdown-option-body--disabled`]:
                this.mergedDisabled
            }
          ],
          onMousemove: this.handleMouseMove,
          onMouseenter: this.handleMouseEnter,
          onMouseleave: this.handleMouseLeave,
          onClick: this.handleClick
        }
const mergedOptionBodyProps: HTMLAttributes = mergeProps(optionBodyProps, ...)
```

最后 `{ ...mergedOptionBodyProps }` 上去

我们这么做是因为为了让更多的地方都享受到类型检查，如果直接对 mergeProps 的结果 as，那么我们就享受不到它参数的类型检查了

2021-09-01 06:26 UTC, Volankey commented on src/dropdown/src/DropdownOption.tsx
> +        props as VNodeProps
HTMLAttributes 和 Data 确实不兼容 这地方也没啥好办法处理
![image](https://user-images.githubusercontent.com/23287363/131622372-65ca5677-a56c-4cd5-923e-5e78773592ba.png)

2021-09-01 16:49 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        props as VNodeProps
我看看咋改吧

2021-09-01 16:50 UTC, merged

2021-09-01 17:03 UTC, 07akioni commented on src/dropdown/src/DropdownOption.tsx
> +        props as VNodeProps
这里面的关键点是让尽量多的地方被类型照顾到，如果放进 mergeProps 直接合并了，就检查不到了